name: data-exp
channels:
  - conda-forge
  - conda
  - defaults
dependencies:
  - numpy=1.21.5
  - openpyxl=3.0.9
  - pandas=1.4.1
  - pandas-profiling=3.1.0
  - pip=22.0.3
  - plotly=5.6.0
  - python=3.9.10
  - streamlit=1.5.1
  - pip:
      - streamlit-pandas-profiling=0.1.3
